location                    = "uksouth"
resource_group_name         = "mate-azure-task-12"
virtual_network_name        = "vnet"
vnet_address_prefix         = "10.0.0.0/16"
subnet_name                 = "default"
subnet_address_prefix       = "10.0.0.0/24"
network_security_group_name = "defaultnsg"
public_ip_address_name      = "linuxboxpip"
vm_name                     = "matebox"
vm_size                     = "Standard_B1s"
ssh_key_public              = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDdZGrZdK1h2zFrTUedM3KgFTUayGtbANXpZ0Tqe3IDgqwB6sffFpmNN5LItWDADkSfoc0xGvBPrgT9pSqbnnK4zayNN/esg2kY9EIwPoBzbhYWAvs+4hDgQRtx3gpppxWZZYQmKg7jXpLCC/BegZnZCRO2qDEuW+QkUUdADYVm8QB+VX+ow7rqp+CjqJcwaX+6hKUXK58Sim7FZtqzeI1QtpVOTUpFYArJkrMkUKeqi3+WSq42s3DILBtfRsveIF8NNNZmb41nkEuZNYIzLHa/jD56CkqmNjR+r2RBHxoMfJQcLYmNlXAXY2OSjYUFRb1lIdAyPr0leimSjfZ80Ge5qBfT0uBKnQ6FqcZS1avDC8WNKaMu4dyIMJ0bGm0uqQ0poioV0UfhI9taPZ7dbY45kG8zaQ9iqpyGYrUWFn89mChDALaX/p41qLH4c0KlUBGIIu4FAH4k+Zo+Xy6DvEKz7omMC7T/KW51k1gmy7k5hQNVGGW+FVlqDEDLLfcG5M1SoEw+iT09NgWUwo/TsCvshWpwpd5aUoktlAKpO1bFIYXgnd4xaUwN4pqeFp5fq5XKDqYYu3da90EVOSMeytmRBwnLLZI2JzCU8fArOqNxEcNErHK8W4e2vHwZT3divEdz9/tpAODVXFePpe77lNZx5+44L4OgKYjcwvRxo0R7Sw== remarkt@GEBRUIK-5LSA2K3"
dns_label                   = "matetask"
github_repo                 = "https://github.com/betterthink/devops_todolist_terraform_task"